version: '3.8'

services:
  prompthub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    container_name: prompthub-app
    
  # 可选：如果需要数据库，可以添加数据库服务
  # database:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: prompthub
  #     POSTGRES_USER: prompthub
  #     POSTGRES_PASSWORD: your_password_here
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
#   postgres_data: